name: Docker Image CI

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build cadc-tomcat
      run: cd cadc-tomcat && docker build . --file Dockerfile --tag cadc-tomcat:$(date +%s)
## TODO: cadc-postgresql-dev relies on the private cadc yum repo
#    - name: Build cadc-postgresql-dev
#      run: cd cadc-postgresql-dev && docker build . --file Dockerfile --tag cadc-postgresql-dev:$(date +%s)
    - name: Build cadc-haproxy-dev
      run: test -d cadc-haproxy-dev && cd cadc-haproxy-dev && docker build . --file Dockerfile --tag cadc-haproxy-dev:$(date +%s)
